<?php

use Illuminate\Database\Seeder;

class AgredidosTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('agredidos')->delete();
        
		\DB::table('agredidos')->insert(array (
			0 => 
			array (
				'id' => 5,
				'alertas_id' => 17,
				'name' => 'Pepe Robos',
				'generos_id' => 3,
				'medios' => 'Casa Presidencial',
				'medios_id' => 11,
				'tiposujetoagredidos_id' => 20,
				'agresions_id' => 4,
			),
			1 => 
			array (
				'id' => 7,
				'alertas_id' => 20,
				'name' => 'www.hondudiario.com',
				'generos_id' => 4,
				'medios' => 'Periodico',
				'medios_id' => 11,
				'tiposujetoagredidos_id' => 8,
				'agresions_id' => 14,
			),
			2 => 
			array (
				'id' => 8,
				'alertas_id' => 21,
				'name' => 'Selvin Martínez',
				'generos_id' => 1,
				'medios' => 'JBN',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 5,
			),
			3 => 
			array (
				'id' => 9,
				'alertas_id' => 22,
				'name' => 'TELECENTRO',
				'generos_id' => 4,
				'medios' => 'TELECENTRO',
				'medios_id' => 4,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 23,
			),
			4 => 
			array (
				'id' => 10,
				'alertas_id' => 16,
				'name' => 'TELECENTRO ',
				'generos_id' => 4,
				'medios' => 'TELECENTRO ',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 15,
				'agresions_id' => 23,
			),
			5 => 
			array (
				'id' => 11,
				'alertas_id' => 23,
				'name' => 'Nery Arteaga',
				'generos_id' => 1,
				'medios' => 'CHN',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 17,
				'agresions_id' => 10,
			),
			6 => 
			array (
				'id' => 12,
				'alertas_id' => 24,
				'name' => 'Mercy Berrios',
				'generos_id' => 1,
				'medios' => 'canal universitario UTV',
				'medios_id' => 9,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 9,
			),
			7 => 
			array (
				'id' => 14,
				'alertas_id' => 18,
				'name' => 'Malvina Salamanca',
				'generos_id' => 2,
				'medios' => 'Casa Presidencial',
				'medios_id' => 10,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			8 => 
			array (
				'id' => 15,
				'alertas_id' => 25,
				'name' => 'Juan Robando',
				'generos_id' => 3,
				'medios' => 'Radio America',
				'medios_id' => 5,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 26,
			),
			9 => 
			array (
				'id' => 16,
				'alertas_id' => 26,
				'name' => 'Medios de Comunicaciòn',
				'generos_id' => 4,
				'medios' => 'Periodistas',
				'medios_id' => 12,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 23,
			),
			10 => 
			array (
				'id' => 18,
				'alertas_id' => 27,
				'name' => 'Periodistas',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicación',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 25,
				'agresions_id' => 4,
			),
			11 => 
			array (
				'id' => 19,
				'alertas_id' => 28,
				'name' => 'Luz Marina Villalobos y Alfredo Landaverde',
				'generos_id' => 4,
			'medios' => 'Periodista y Analista (Fuente informativa)',
				'medios_id' => 17,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 19,
			),
			12 => 
			array (
				'id' => 20,
				'alertas_id' => 29,
				'name' => 'José Ricardo Rosales',
				'generos_id' => 1,
				'medios' => 'Abogado',
				'medios_id' => 17,
				'tiposujetoagredidos_id' => 20,
				'agresions_id' => 1,
			),
			13 => 
			array (
				'id' => 21,
				'alertas_id' => 30,
				'name' => 'Matías Valle',
				'generos_id' => 1,
				'medios' => 'Diversos',
				'medios_id' => 15,
				'tiposujetoagredidos_id' => 4,
				'agresions_id' => 1,
			),
			14 => 
			array (
				'id' => 22,
				'alertas_id' => 31,
				'name' => 'Escritores nacionales',
				'generos_id' => 4,
				'medios' => 'Cultura Artisitica',
				'medios_id' => 14,
				'tiposujetoagredidos_id' => 17,
				'agresions_id' => 23,
			),
			15 => 
			array (
				'id' => 23,
				'alertas_id' => 32,
				'name' => 'Gilda Silvestrucci',
				'generos_id' => 2,
				'medios' => 'Radio',
				'medios_id' => 16,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 4,
			),
			16 => 
			array (
				'id' => 24,
				'alertas_id' => 33,
				'name' => 'Periodistas',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicaciòn',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 21,
			),
			17 => 
			array (
				'id' => 25,
				'alertas_id' => 34,
				'name' => 'Itsmania Pineda Platero',
				'generos_id' => 2,
				'medios' => 'Digital',
				'medios_id' => 16,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 14,
			),
			18 => 
			array (
				'id' => 26,
				'alertas_id' => 35,
				'name' => 'Vitalino Álvarez',
				'generos_id' => 1,
				'medios' => 'Diversos',
				'medios_id' => 15,
				'tiposujetoagredidos_id' => 4,
				'agresions_id' => 2,
			),
			19 => 
			array (
				'id' => 27,
				'alertas_id' => 36,
				'name' => 'Esdras Amado López',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 9,
				'agresions_id' => 21,
			),
			20 => 
			array (
				'id' => 28,
				'alertas_id' => 37,
				'name' => 'Menor de edad',
				'generos_id' => 2,
				'medios' => 'Comunidad de Rigores',
				'medios_id' => 15,
				'tiposujetoagredidos_id' => 16,
				'agresions_id' => 8,
			),
			21 => 
			array (
				'id' => 29,
				'alertas_id' => 38,
				'name' => 'Grupo de periodistas',
				'generos_id' => 4,
				'medios' => 'Medio de Comunicación',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 23,
			),
			22 => 
			array (
				'id' => 30,
				'alertas_id' => 39,
				'name' => 'Grupo de Periodistas',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicación',
				'medios_id' => 10,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 7,
			),
			23 => 
			array (
				'id' => 31,
				'alertas_id' => 40,
				'name' => 'Ivis Alvarado ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 12,
			),
			24 => 
			array (
				'id' => 32,
				'alertas_id' => 41,
				'name' => 'Danilo Osmaro Castellanos',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 5,
			),
			25 => 
			array (
				'id' => 33,
				'alertas_id' => 42,
				'name' => 'Luis Rodríguez y Javier Villalobos ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 5,
			),
			26 => 
			array (
				'id' => 34,
				'alertas_id' => 43,
				'name' => 'Ramón Cabrera',
				'generos_id' => 1,
				'medios' => 'Sistema de Cable',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 7,
				'agresions_id' => 5,
			),
			27 => 
			array (
				'id' => 35,
				'alertas_id' => 44,
				'name' => 'Luis Antonio Henríquez',
				'generos_id' => 1,
				'medios' => 'Caricaturista',
				'medios_id' => 6,
				'tiposujetoagredidos_id' => 17,
				'agresions_id' => 12,
			),
			28 => 
			array (
				'id' => 36,
				'alertas_id' => 45,
				'name' => 'Luis Ortiz ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 9,
			),
			29 => 
			array (
				'id' => 37,
				'alertas_id' => 46,
				'name' => 'Jóvenes artistas',
				'generos_id' => 4,
				'medios' => 'Cultura artisitica',
				'medios_id' => 8,
				'tiposujetoagredidos_id' => 17,
				'agresions_id' => 21,
			),
			30 => 
			array (
				'id' => 38,
				'alertas_id' => 47,
				'name' => 'Saira Fabiola Almendares ',
				'generos_id' => 2,
				'medios' => 'Estudiante de Periodismo',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			31 => 
			array (
				'id' => 39,
				'alertas_id' => 48,
				'name' => 'Mavis Ethel Cruz ',
				'generos_id' => 2,
				'medios' => 'Radio',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 4,
			),
			32 => 
			array (
				'id' => 41,
				'alertas_id' => 49,
				'name' => 'Erick Euceda Ortez',
				'generos_id' => 1,
				'medios' => 'Estudiante de periodismo',
				'medios_id' => 14,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 2,
			),
			33 => 
			array (
				'id' => 42,
				'alertas_id' => 50,
				'name' => 'Luis Ortiz ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 21,
			),
			34 => 
			array (
				'id' => 43,
				'alertas_id' => 51,
				'name' => 'Fausto Elio Hernández ',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			35 => 
			array (
				'id' => 44,
				'alertas_id' => 52,
				'name' => 'Luis Ortiz',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 19,
			),
			36 => 
			array (
				'id' => 45,
				'alertas_id' => 53,
				'name' => 'Alex Roberto Sabillón Gómez',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 4,
			),
			37 => 
			array (
				'id' => 46,
				'alertas_id' => 54,
				'name' => 'Elvis Guzmán',
				'generos_id' => 1,
				'medios' => 'Ministerio Publico',
				'medios_id' => 11,
				'tiposujetoagredidos_id' => 6,
				'agresions_id' => 5,
			),
			38 => 
			array (
				'id' => 47,
				'alertas_id' => 55,
				'name' => 'José Modesto Acosta',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 7,
			),
			39 => 
			array (
				'id' => 48,
				'alertas_id' => 56,
				'name' => 'Canal 36',
				'generos_id' => 4,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 26,
				'agresions_id' => 11,
			),
			40 => 
			array (
				'id' => 49,
				'alertas_id' => 57,
				'name' => 'Periodista',
				'generos_id' => 2,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 17,
			),
			41 => 
			array (
				'id' => 50,
				'alertas_id' => 58,
				'name' => 'Eleana Borjas ',
				'generos_id' => 2,
				'medios' => 'Digital',
				'medios_id' => 7,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 26,
			),
			42 => 
			array (
				'id' => 51,
				'alertas_id' => 59,
				'name' => 'Radios comunitarias “La Voz Lenca” y “Radio Guarajambala”',
				'generos_id' => 4,
				'medios' => 'Radio',
				'medios_id' => 9,
				'tiposujetoagredidos_id' => 29,
				'agresions_id' => 14,
			),
			43 => 
			array (
				'id' => 52,
				'alertas_id' => 60,
				'name' => 'Kelly Núñez, Erlin Gutiérrez y Miguel Ángel Aguilar',
				'generos_id' => 4,
				'medios' => 'Dirigentes estudiantiles',
				'medios_id' => 11,
				'tiposujetoagredidos_id' => 15,
				'agresions_id' => 21,
			),
			44 => 
			array (
				'id' => 53,
				'alertas_id' => 61,
				'name' => 'Rony Espinoza',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 4,
			),
			45 => 
			array (
				'id' => 54,
				'alertas_id' => 62,
				'name' => 'Grupo de periodistas',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicación',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 25,
				'agresions_id' => 26,
			),
			46 => 
			array (
				'id' => 55,
				'alertas_id' => 63,
				'name' => 'Noé Valladares, ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 12,
				'agresions_id' => 1,
			),
			47 => 
			array (
				'id' => 56,
				'alertas_id' => 64,
				'name' => 'Dina Meza Elvir',
				'generos_id' => 2,
				'medios' => 'ONG/DDHH',
				'medios_id' => 8,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 5,
			),
			48 => 
			array (
				'id' => 57,
				'alertas_id' => 65,
				'name' => 'Elder Joel Aguilar',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 4,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 2,
			),
			49 => 
			array (
				'id' => 58,
				'alertas_id' => 66,
				'name' => 'Santiago Cerna ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 4,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 5,
			),
			50 => 
			array (
				'id' => 59,
				'alertas_id' => 67,
				'name' => 'Selvin Martínez ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 10,
			),
			51 => 
			array (
				'id' => 60,
				'alertas_id' => 68,
				'name' => 'Edgardo Castro',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 12,
				'agresions_id' => 5,
			),
			52 => 
			array (
				'id' => 61,
				'alertas_id' => 69,
				'name' => 'Erick Martínez Ávila',
				'generos_id' => 3,
				'medios' => 'ONG/DDHH',
				'medios_id' => 8,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			53 => 
			array (
				'id' => 62,
				'alertas_id' => 70,
				'name' => 'Alfredo Villatoro',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 5,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 17,
			),
			54 => 
			array (
				'id' => 63,
				'alertas_id' => 71,
				'name' => 'Grupo de periodistas',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicación',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 4,
			),
			55 => 
			array (
				'id' => 69,
				'alertas_id' => 72,
				'name' => 'Alfredo Villatoro',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 5,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			56 => 
			array (
				'id' => 71,
				'alertas_id' => 73,
				'name' => 'Dilcia Moreno',
				'generos_id' => 2,
				'medios' => 'Esposa de Comunicador Social',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 17,
			),
			57 => 
			array (
				'id' => 72,
				'alertas_id' => 74,
				'name' => 'Antonio Cabrera ',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 5,
			),
			58 => 
			array (
				'id' => 73,
				'alertas_id' => 75,
				'name' => 'David Romero y  Esdras Amado López ',
				'generos_id' => 1,
				'medios' => 'Diversos',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 8,
			),
			59 => 
			array (
				'id' => 74,
				'alertas_id' => 76,
				'name' => 'Ángel Villatoro',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 5,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 19,
			),
			60 => 
			array (
				'id' => 75,
				'alertas_id' => 77,
				'name' => 'Luis Ortiz ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 19,
			),
			61 => 
			array (
				'id' => 76,
				'alertas_id' => 78,
				'name' => 'Adalid Romero',
				'generos_id' => 1,
				'medios' => 'Iglesia Catolica',
				'medios_id' => 17,
				'tiposujetoagredidos_id' => 23,
				'agresions_id' => 3,
			),
			62 => 
			array (
				'id' => 77,
				'alertas_id' => 79,
				'name' => 'Leonardo Aguilar y Gerardo Chevez ',
				'generos_id' => 1,
				'medios' => 'Medios de Comunicacion',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 7,
			),
			63 => 
			array (
				'id' => 79,
				'alertas_id' => 80,
				'name' => 'Uriel Gudiel Rodríguez',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 3,
				'agresions_id' => 19,
			),
			64 => 
			array (
				'id' => 80,
				'alertas_id' => 81,
				'name' => 'Edwin Murillo',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 4,
				'tiposujetoagredidos_id' => 3,
				'agresions_id' => 17,
			),
			65 => 
			array (
				'id' => 81,
				'alertas_id' => 82,
				'name' => 'Juan Vásquez y Sotero Chavarría',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 9,
				'tiposujetoagredidos_id' => 27,
				'agresions_id' => 2,
			),
			66 => 
			array (
				'id' => 82,
				'alertas_id' => 83,
				'name' => 'Sandra Maribel Sanchez ',
				'generos_id' => 2,
				'medios' => 'Radio',
				'medios_id' => 16,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 19,
			),
			67 => 
			array (
				'id' => 83,
				'alertas_id' => 85,
				'name' => 'David Corea',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 5,
			),
			68 => 
			array (
				'id' => 84,
				'alertas_id' => 86,
				'name' => 'Adonis Felipe Bueso Gutiérrez ',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 9,
				'tiposujetoagredidos_id' => 27,
				'agresions_id' => 1,
			),
			69 => 
			array (
				'id' => 85,
				'alertas_id' => 87,
				'name' => 'Selvin Martínez',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 2,
			),
			70 => 
			array (
				'id' => 86,
				'alertas_id' => 88,
				'name' => 'Selvin Martínez',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 10,
			),
			71 => 
			array (
				'id' => 87,
				'alertas_id' => 89,
				'name' => 'Luis Ortiz ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 27,
			),
			72 => 
			array (
				'id' => 88,
				'alertas_id' => 90,
				'name' => 'Dick Emanuelsson',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 10,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 27,
			),
			73 => 
			array (
				'id' => 89,
				'alertas_id' => 91,
				'name' => 'Medios de comunicación',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicación',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 21,
				'agresions_id' => 27,
			),
			74 => 
			array (
				'id' => 90,
				'alertas_id' => 92,
				'name' => 'José Encarnación Chinchilla y Radio Progreso',
				'generos_id' => 4,
				'medios' => 'Radio',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 25,
				'agresions_id' => 7,
			),
			75 => 
			array (
				'id' => 91,
				'alertas_id' => 93,
				'name' => 'Periodistas Varios',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicacion',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 25,
				'agresions_id' => 28,
			),
			76 => 
			array (
				'id' => 92,
				'alertas_id' => 94,
				'name' => 'Lidieth Díaz, Fidelina Sandoval y Cesar Maldonado',
				'generos_id' => 4,
				'medios' => 'Diversos',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 9,
			),
			77 => 
			array (
				'id' => 93,
				'alertas_id' => 95,
				'name' => 'Ariel D´Viciente',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 4,
			),
			78 => 
			array (
				'id' => 94,
				'alertas_id' => 96,
				'name' => 'José Noel Canales ',
				'generos_id' => 1,
				'medios' => 'Digital',
				'medios_id' => 7,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			79 => 
			array (
				'id' => 95,
				'alertas_id' => 97,
				'name' => 'Miguel Dubón',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 7,
			),
			80 => 
			array (
				'id' => 96,
				'alertas_id' => 98,
				'name' => 'Cesar Alvarenga',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 5,
			),
			81 => 
			array (
				'id' => 97,
				'alertas_id' => 99,
				'name' => 'Alex Roberto Sabillón Chávez ',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 7,
			),
			82 => 
			array (
				'id' => 98,
				'alertas_id' => 100,
				'name' => 'Alex Roberto Sabillón Chávez',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 7,
			),
			83 => 
			array (
				'id' => 99,
				'alertas_id' => 101,
				'name' => 'Vitalino Álvarez',
				'generos_id' => 1,
				'medios' => 'Vocero',
				'medios_id' => 15,
				'tiposujetoagredidos_id' => 4,
				'agresions_id' => 7,
			),
			84 => 
			array (
				'id' => 100,
				'alertas_id' => 102,
				'name' => 'Julio Cesar Guifarro Casaleno ',
				'generos_id' => 1,
				'medios' => 'Vocero',
				'medios_id' => 11,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			85 => 
			array (
				'id' => 101,
				'alertas_id' => 103,
				'name' => 'Grupo de Periodistas',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicacion',
				'medios_id' => 1,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 23,
			),
			86 => 
			array (
				'id' => 102,
				'alertas_id' => 104,
				'name' => 'Eduardo Coto Barnica',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 2,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 4,
			),
			87 => 
			array (
				'id' => 103,
				'alertas_id' => 105,
				'name' => 'Alex sabillon',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 9,
			),
			88 => 
			array (
				'id' => 104,
				'alertas_id' => 106,
				'name' => 'Antonio Trejo Cabrera ',
				'generos_id' => 1,
				'medios' => 'Abogado ',
				'medios_id' => 15,
				'tiposujetoagredidos_id' => 20,
				'agresions_id' => 1,
			),
			89 => 
			array (
				'id' => 105,
				'alertas_id' => 107,
				'name' => 'Karla Zelaya',
				'generos_id' => 2,
				'medios' => 'Vocera',
				'medios_id' => 15,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 5,
			),
			90 => 
			array (
				'id' => 106,
				'alertas_id' => 108,
				'name' => 'Edgardo Antonio Escoto Amador',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 4,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 3,
			),
			91 => 
			array (
				'id' => 107,
				'alertas_id' => 109,
				'name' => 'Elizabeth Zuniga',
				'generos_id' => 2,
				'medios' => 'Radio',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 18,
			),
			92 => 
			array (
				'id' => 108,
				'alertas_id' => 110,
				'name' => 'Gremio Magisterial',
				'generos_id' => 4,
				'medios' => 'Gremio Magisterial',
				'medios_id' => 14,
				'tiposujetoagredidos_id' => 16,
				'agresions_id' => 18,
			),
			93 => 
			array (
				'id' => 109,
				'alertas_id' => 111,
				'name' => 'www.hondudiario.com ',
				'generos_id' => 4,
				'medios' => 'Digital',
				'medios_id' => 7,
				'tiposujetoagredidos_id' => 8,
				'agresions_id' => 14,
			),
			94 => 
			array (
				'id' => 110,
				'alertas_id' => 112,
				'name' => 'Selvin Martínez',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 19,
			),
			95 => 
			array (
				'id' => 111,
				'alertas_id' => 113,
				'name' => 'Pobladores ',
				'generos_id' => 4,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 27,
				'agresions_id' => 26,
			),
			96 => 
			array (
				'id' => 112,
				'alertas_id' => 114,
				'name' => 'Medios de Comunicacion',
				'generos_id' => 4,
				'medios' => 'Medios de Comunicacion',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 2,
				'agresions_id' => 23,
			),
			97 => 
			array (
				'id' => 113,
				'alertas_id' => 115,
				'name' => 'Nery Arteaga y Ninfa Gallo ',
				'generos_id' => 4,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 12,
			),
			98 => 
			array (
				'id' => 114,
				'alertas_id' => 116,
				'name' => 'Ángel Edgardo López Fiallos ',
				'generos_id' => 1,
				'medios' => 'Radio',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 1,
			),
			99 => 
			array (
				'id' => 115,
				'alertas_id' => 117,
				'name' => 'Mercy Berrios y al camarógrafo David Coello',
				'generos_id' => 4,
				'medios' => 'TV',
				'medios_id' => 14,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 4,
			),
			100 => 
			array (
				'id' => 116,
				'alertas_id' => 118,
				'name' => 'Juana Dolores Valenzuela Calix',
				'generos_id' => 2,
				'medios' => 'Digital',
				'medios_id' => 7,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 5,
			),
			101 => 
			array (
				'id' => 117,
				'alertas_id' => 119,
				'name' => 'C-Libre',
				'generos_id' => 4,
				'medios' => 'ONG/DDHH',
				'medios_id' => 8,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 23,
			),
			102 => 
			array (
				'id' => 118,
				'alertas_id' => 84,
				'name' => 'Ariel D`Viciente',
				'generos_id' => 1,
				'medios' => 'TV',
				'medios_id' => 13,
				'tiposujetoagredidos_id' => 1,
				'agresions_id' => 21,
			),
		));
	}

}
